### ISSUE TITLE
Add S3 client-side encryption support 

### ISSUE THREAD

**Issue by krisis** [minio/minio-hs#60]
Ref: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html

**Comment by harshavardhana** [comment]
This plan has been deprecated, we only support server-side encryption for now.

**Comment by cgoeller** [comment]
The Minio Website (https://www.minio.io/features.html) states that both is supported:

### Encryption and Tamper-Proof
Minio provides confidentiality, integrity and authenticity assurances for encrypted data with negligible performance overhead. **Both server side and client side encryption are supported** using...

**Comment by harshavardhana** [comment]
It is supported already @cgoeller

**Comment by martinm82** [comment]
Is client-side encryption really supported? I cannot find anything in the minio docs.

**Comment by donatello** [comment]
@martinm82 MinIO supports server side encryption similar to AWS S3. For client side encryption, no additional support is required from the server. All you have to do is to PUTobject the client encrypted stream into a MinIO server.
